# Generated by Django 5.2.9 on 2025-12-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_all_messages', 'Can view all messages')]},
        ),
    ]
